### ISSUE TITLE
Update to be available via NPM and/or Bower

### ISSUE THREAD

**Issue by tylerdmace** [DavydeVries/PoGO-Awesome#3]
It would be really awesome to be able to install this via NPM.

**Comment by DavydeVries** [comment]
I'm not familiar with creating packages. I give it a try with NPM and bower.
In package.json at line 5 I'm not sure that `"main": "index.js"` is right.

I have created a separated [branch (install-packages)](https://github.com/DavydeVries/PoGO-Awesome/tree/install-packages) for this.
@tylerdmace can you check this?
